<?php

/**
 * Campaign.
 * 
 * Generated by Gii. Modified.
 * 
 * @author Gemblue
 */

namespace app\models;

use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;

class Campaign extends ActiveRecord
{
    /**
     * Like before/after model method.
     * 
     * In Yii, it's called behaviours.
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * Join with users ..
     * 
     * @return Object
     */
    public function getUser()
    {
        return $this->hasOne(Users::className(), ['id' => 'user_id']);
    }
}